# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
cidr                   = "10.0.0.0/16"
enable_dns_hostnames   = true
enable_dns_support     = true
enable_nat_gateway     = true
private_subnets        = ["10.0.0.0/20", "10.0.16.0/20", "10.0.32.0/20"]
region                 = "eu-west-1"
single_nat_gateway     = true
azs                    = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
create_egress_only_igw = true
public_subnets         = ["10.0.48.0/24", "10.0.49.0/24", "10.0.50.0/24"]
